### ISSUE TITLE
-bash: pocket-auth: command not found

### ISSUE THREAD

**Issue by TheChrisVela** [mheap/pocket-auth-cli#1]
I install the package with NPM 

`npm install -g pocket-auth`

and then I see it is sucesfully installed.

```
> + pocket-auth@1.2.0
```

then when I try to run the command from the command line

`pocket-auth 1234-abcd1234abcd1234abcd1234 `

I get the error message 

`-bash: pocket-auth: command not found`

**Comment by mheap** [comment]
Thanks for reporting. The package name was incorrect in the README
